services:
  db:
    image: postgres:latest
    container_name: event-db
    environment:
      POSTGRES_USER: yakushev
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: EventWebAPI
    ports:
      - '5433:5432'
    networks:
      - network

  redis:
    image: redis:latest
    container_name: event-redis
    ports:
      - '6379:6379'
    networks:
      - network

networks:
  network:
    driver: bridge
